# workflow name
name: Deploy Pages

# fire on
on: [push, pull_request, workflow_dispatch]

# stuff to do
jobs:
  # Install/Process Repository
  install-process-repository:
    name: Process Repository
    runs-on: ${{ matrix.os-name }}

    # VM settings
    #  os & python versions
    strategy:
      matrix:
        # pages on one OS
        os-name: [ubuntu-latest]
        python-version: [3.8]

    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v2
      # install python
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - run: |
          python --version
      # Prepare Repository
      - name: Prepare Repository
        run: |
          python ./resources/ci/common/prepare_repository.py
      # Cleanup Workspace
      - name: Cleanup Workspace
        run: |
          python ./resources/ci/common/cleanup.py
      # upload pages artifact for later step
      - name: Upload Pages Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pages-${{ matrix.os-name }}
          path: ./

  # Install/Publish Pages
  install-publish-pages:
    name: Publish Pages
    runs-on: ${{ matrix.os-name }}
    needs: [ install-process-repository ]

    # VM settings
    #  os & python versions
    strategy:
      matrix:
        # pages on one OS
        os-name: [ubuntu-latest]
        python-version: [3.8]

    steps:
      # checkout gh-pages
      - name: Checkout commit
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      # download pages artifact
      - name: Download Pages Artifact
        uses: actions/download-artifact@v2
        with:
          name: pages-${{ matrix.os-name }}
          path: ./
      # Prepare for GH-Pages
      - name: Prepare for GH-Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
      # List Differences
      - name: List Differences
        run: |
          git diff --name-status --cached
      # Set Commit
      - name: Set Commit
        run: |
          git commit -q -F commit.txt || echo ""
          git log || echo "Failed to print Git Log"
      # Push to GH-Pages
      - name: Push to GH-Pages (PUBLISH)
        run: |
          git push || echo "Failed to push to GitHub Pages"
        if: contains(github.ref, 'publish')
